# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-redis-operator
  description: "This component installs `redis-operator` for EKS clusters"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







